name: Profile Metrics

on:
  schedule:
    - cron: "0 */12 * * *" # atualiza a cada 12h
  workflow_dispatch:
  push:
    branches: [main] # roda quando vocÃª fizer push na main
    paths:
      - README.md
      - .github/workflows/metrics.yml

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics (public + private)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }} # seu PAT classic
          committer_token: ${{ secrets.GITHUB_TOKEN }} # para commitar o SVG
          user: oliveira-a-rafael
          filename: github-metrics.svg

          template: classic
          config_timezone: America/Sao_Paulo
          config_animations: yes
          config_twemoji: yes
          optimize: svg

          base: header, repositories
          repositories_affiliations: owner, collaborator, organization_member
          repositories_forks: yes
